# Generated by Django 4.2.1 on 2023-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_marca_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.FloatField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.ManyToManyField(null=True, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='products/statics/imagenes'),
        ),
    ]
