# Generated by Django 4.2.1 on 2023-05-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_precio_alter_product_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa'), ('calzado', 'Calzado'), ('electronica', 'Electronica'), ('joyeria', 'Joyeria'), ('herramientas', 'Herramientas'), ('electrodomesticos', 'Eletrodomesticos')], default='ropa', max_length=20),
        ),
    ]
